//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public int id { get; set; }
        public Nullable<int> id_detalle_compra { get; set; }
        public Nullable<int> stock_producto { get; set; }
        public Nullable<int> cantidad_compra { get; set; }
        public Nullable<System.DateTime> fecha_ingreso_almacen { get; set; }
    
        public virtual Detalle_compra Detalle_compra { get; set; }
    }
}
