//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja_dia
    {
        public int id { get; set; }
        public int id_caja { get; set; }
        public int usuario_apertura { get; set; }
        public Nullable<int> usuario_cierre { get; set; }
        public bool estado_apertura_caja_dia { get; set; }
        public decimal saldo_inicial { get; set; }
        public Nullable<decimal> saldo_final { get; set; }
        public Nullable<decimal> saldo_diferencia { get; set; }
        public Nullable<decimal> saldo_egreso_caja_dia { get; set; }
        public System.DateTime fecha_apertura { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<System.DateTime> fapertura_caja_dia { get; set; }
        public Nullable<System.DateTime> fcierre_caja_dia { get; set; }
        public bool estado_caja_dia { get; set; }
    
        public virtual Caja Caja { get; set; }
    }
}
