//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        public int id { get; set; }
        public string tipo_comprobante { get; set; }
        public string serie_comprobante { get; set; }
        public int correlativo_comprobante { get; set; }
        public bool estado_comprobante { get; set; }
    }
}
