//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int id { get; set; }
        public decimal precio_delivery { get; set; }
        public decimal igv_actual { get; set; }
        public decimal porcentaje_sobre_factura { get; set; }
        public bool estado_configuracion { get; set; }
    }
}
