//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egreso
    {
        public int id { get; set; }
        public int id_usuario { get; set; }
        public int id_concepto { get; set; }
        public int id_caja_dia { get; set; }
        public System.DateTime fecha_registro_egreso { get; set; }
        public decimal monto_egreso { get; set; }
        public Nullable<bool> estado_egreso { get; set; }
    
        public virtual Concepto Concepto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
