//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion_Concepto
    {
        public int id_concepto { get; set; }
        public int id_liquidacion { get; set; }
        public string id_tipo_liquidacion { get; set; }
        public string descripcion_concepto { get; set; }
        public int cantidad_concepto { get; set; }
        public decimal subtotal_precio_concepto { get; set; }
        public decimal igv_precio_concepto { get; set; }
        public decimal total_precio_concepto { get; set; }
    }
}
