//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion_Consumo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Liquidacion_Consumo()
        {
            this.Consumo_habitacion = new HashSet<Consumo_habitacion>();
        }
    
        public int id_liquidacion { get; set; }
        public Nullable<int> id_caja_dia { get; set; }
        public string cliente_liquidacion { get; set; }
        public string dni_liquidacion { get; set; }
        public string ruc_liquidacion { get; set; }
        public string razon_social_liquidacion { get; set; }
        public string direccion_liquidacion { get; set; }
        public string tipo_comprobante_liquidacion { get; set; }
        public string serie_liquidacion { get; set; }
        public string correlativo_liquidacion { get; set; }
        public string forma_pago_liquidacion { get; set; }
        public System.DateTime fecha_liquidacion { get; set; }
        public decimal sub_total_liquidacion { get; set; }
        public decimal igv_liquidacion { get; set; }
        public decimal total_liquidacion { get; set; }
        public Nullable<decimal> consumo_liquidacion { get; set; }
        public string referencia_liquidacion { get; set; }
        public string ntarjeta_liquidacion { get; set; }
        public Nullable<bool> estado_tarjeta { get; set; }
        public bool estado_liquidacion { get; set; }
        public Nullable<bool> caja_liquidacion { get; set; }
        public Nullable<bool> consolidado_liquidacion { get; set; }
        public Nullable<bool> sobre_factura_liquidacion { get; set; }
        public Nullable<bool> situacion_liquidacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consumo_habitacion> Consumo_habitacion { get; set; }
    }
}
