//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalle_compra = new HashSet<Detalle_compra>();
        }
    
        public int id { get; set; }
        public int id_categoria { get; set; }
        public string nombre_producto { get; set; }
        public decimal precio_producto { get; set; }
        public string tipo_producto { get; set; }
        public bool estado_producto { get; set; }
        public Nullable<int> stock_producto { get; set; }
    
        public virtual Categoria_producto Categoria_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_compra> Detalle_compra { get; set; }
    }
}
