//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva_Historica
    {
        public int id { get; set; }
        public Nullable<int> id_reserva { get; set; }
        public Nullable<int> id_huesped { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<System.DateTime> fecha_in { get; set; }
        public Nullable<System.DateTime> fecha_out { get; set; }
    }
}
