//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifa_habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarifa_habitacion()
        {
            this.HabitacionTarifa = new HashSet<HabitacionTarifa>();
        }
    
        public int id { get; set; }
        public string nombre_tarifa_habitacion { get; set; }
        public decimal precio_tarifa_habitacion { get; set; }
        public bool estado_tarifa_habitacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HabitacionTarifa> HabitacionTarifa { get; set; }
    }
}
