//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistaCabeceraBoleta
    {
        public int id { get; set; }
        public Nullable<int> id_huesped { get; set; }
        public string nombre_empresa { get; set; }
        public string ruc_empresa { get; set; }
        public string direccion_empresa { get; set; }
        public Nullable<int> id_reserva { get; set; }
        public Nullable<int> indice { get; set; }
        public Nullable<int> id_grupo { get; set; }
    }
}
