//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistaConsumoLiquidacion
    {
        public int id { get; set; }
        public Nullable<int> id_liquidacion_consumo { get; set; }
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public int cantidad_servicio_habitacion { get; set; }
        public decimal precio_servicio_habitacion { get; set; }
        public Nullable<decimal> total_consumo { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
