//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistaUsuarioList
    {
        public int id { get; set; }
        public int id_rol { get; set; }
        public string nombre_rol { get; set; }
        public string paterno_usuario { get; set; }
        public string materno_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string login_usuario { get; set; }
        public byte[] password_usuario { get; set; }
    }
}
