//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistaProductoList
    {
        public int id { get; set; }
        public int id_categoria { get; set; }
        public string nombre_categoria_producto { get; set; }
        public string nombre_producto { get; set; }
        public decimal precio_producto { get; set; }
        public string tipo_producto { get; set; }
        public int consumo { get; set; }
        public int otro { get; set; }
        public Nullable<int> stock_producto { get; set; }
    }
}
