//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistaEgresoList
    {
        public int id { get; set; }
        public int id_usuario { get; set; }
        public string login_usuario { get; set; }
        public int id_concepto { get; set; }
        public string descripcion_concepto { get; set; }
        public int id_caja_dia { get; set; }
        public System.DateTime fecha_registro_egreso { get; set; }
        public decimal monto_egreso { get; set; }
    }
}
