//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistaConsultaHuesped
    {
        public int id { get; set; }
        public string completo_huesped { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string razon_social { get; set; }
        public string paterno_huesped { get; set; }
        public string materno_huesped { get; set; }
        public string nombre_huesped { get; set; }
        public string dni_huesped { get; set; }
        public string celular_huesped { get; set; }
        public string ruc { get; set; }
        public string email_huesped { get; set; }
    }
}
