//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class vistaHabitacionHistoricas
    {
        public int id { get; set; }
        public Nullable<int> codigo_reserva { get; set; }
        public Nullable<int> id_tarifa_habitacion { get; set; }
        public int id_habitacion { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_hotelera { get; set; }
        public Nullable<System.DateTime> fecha_checkIn { get; set; }
        public Nullable<System.DateTime> fecha_checkOut { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<bool> estado_pago_reserva { get; set; }
        public string estado_habitacion_reserva { get; set; }
        public Nullable<bool> estado_fecha { get; set; }
        public Nullable<bool> estado_reserva { get; set; }
        public Nullable<bool> estado_auto { get; set; }
        public Nullable<int> grupo_reserva { get; set; }
        public string observacion_reserva { get; set; }
    }
}
