//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using CapaEntidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SysHotelEntities : DbContext
    {
        public SysHotelEntities()
            : base("name=SysHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacen> Almacen { get; set; }
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<Categoria_producto> Categoria_producto { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Concepto> Concepto { get; set; }
        public virtual DbSet<Detalle_compra> Detalle_compra { get; set; }
        public virtual DbSet<Egreso> Egreso { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Habitacion> Habitacion { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<vistaEgresoList> vistaEgresoList { get; set; }
        public virtual DbSet<vistaUsuarioList> vistaUsuarioList { get; set; }
        public virtual DbSet<Calificacion> Calificacion { get; set; }
        public virtual DbSet<vistaClasificacion> vistaClasificacion { get; set; }
        public virtual DbSet<vistaTotalPuntos> vistaTotalPuntos { get; set; }
        public virtual DbSet<vistaHuespedReserva> vistaHuespedReserva { get; set; }
        public virtual DbSet<vistaProductoList> vistaProductoList { get; set; }
        public virtual DbSet<Servicio_habitacion> Servicio_habitacion { get; set; }
        public virtual DbSet<vistaClasificacionHuesped> vistaClasificacionHuesped { get; set; }
        public virtual DbSet<Caja_dia> Caja_dia { get; set; }
        public virtual DbSet<vistaHabitacionTarifa> vistaHabitacionTarifa { get; set; }
        public virtual DbSet<vistaHabitacion> vistaHabitacion { get; set; }
        public virtual DbSet<HabitacionTarifa> HabitacionTarifa { get; set; }
        public virtual DbSet<Tarifa_habitacion> Tarifa_habitacion { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
        public virtual DbSet<Detalle_reserva> Detalle_reserva { get; set; }
        public virtual DbSet<vistaCabeceraFactura> vistaCabeceraFactura { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<vistaHabitacionesAlquiladas> vistaHabitacionesAlquiladas { get; set; }
        public virtual DbSet<vistaPedidoList> vistaPedidoList { get; set; }
        public virtual DbSet<vistaLiquidacion> vistaLiquidacion { get; set; }
        public virtual DbSet<vistaUnirFactura> vistaUnirFactura { get; set; }
        public virtual DbSet<vistaBusquedaReservas> vistaBusquedaReservas { get; set; }
        public virtual DbSet<vistaHabitacionHistoricas> vistaHabitacionHistoricas { get; set; }
        public virtual DbSet<vistaReservaHistorica> vistaReservaHistorica { get; set; }
        public virtual DbSet<Monto_A_Cuenta> Monto_A_Cuenta { get; set; }
        public virtual DbSet<Adicionales> Adicionales { get; set; }
        public virtual DbSet<vistaConsumoLiquidacion> vistaConsumoLiquidacion { get; set; }
        public virtual DbSet<Consumo_habitacion> Consumo_habitacion { get; set; }
        public virtual DbSet<vistaLiquidacionConsumo> vistaLiquidacionConsumo { get; set; }
        public virtual DbSet<Dolar> Dolar { get; set; }
        public virtual DbSet<Reserva_Historica> Reserva_Historica { get; set; }
        public virtual DbSet<vistaCabeceraBoleta> vistaCabeceraBoleta { get; set; }
        public virtual DbSet<Comprobante> Comprobante { get; set; }
        public virtual DbSet<vistaComprobante> vistaComprobante { get; set; }
        public virtual DbSet<Liquidacion_Concepto> Liquidacion_Concepto { get; set; }
        public virtual DbSet<Huesped> Huesped { get; set; }
        public virtual DbSet<vistaConsultaHuesped> vistaConsultaHuesped { get; set; }
        public virtual DbSet<vistaHuespedList> vistaHuespedList { get; set; }
        public virtual DbSet<Liquidacion> Liquidacion { get; set; }
        public virtual DbSet<Liquidacion_Consumo> Liquidacion_Consumo { get; set; }
    
        public virtual int pa_CambiarConfiguracion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CambiarConfiguracion");
        }
    
        public virtual int pa_InsertarConcepto(Nullable<int> id_usuario, Nullable<int> id_concepto, Nullable<int> id_caja_dia, Nullable<decimal> monto_egreso)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var id_conceptoParameter = id_concepto.HasValue ?
                new ObjectParameter("id_concepto", id_concepto) :
                new ObjectParameter("id_concepto", typeof(int));
    
            var id_caja_diaParameter = id_caja_dia.HasValue ?
                new ObjectParameter("id_caja_dia", id_caja_dia) :
                new ObjectParameter("id_caja_dia", typeof(int));
    
            var monto_egresoParameter = monto_egreso.HasValue ?
                new ObjectParameter("monto_egreso", monto_egreso) :
                new ObjectParameter("monto_egreso", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_InsertarConcepto", id_usuarioParameter, id_conceptoParameter, id_caja_diaParameter, monto_egresoParameter);
        }
    
        public virtual int pa_CambiarEstado(Nullable<int> id, string estado_habitacion_reserva)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var estado_habitacion_reservaParameter = estado_habitacion_reserva != null ?
                new ObjectParameter("estado_habitacion_reserva", estado_habitacion_reserva) :
                new ObjectParameter("estado_habitacion_reserva", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CambiarEstado", idParameter, estado_habitacion_reservaParameter);
        }
    
        public virtual ObjectResult<pa_UltimaObservacion_Result> pa_UltimaObservacion(string dni_huesped)
        {
            var dni_huespedParameter = dni_huesped != null ?
                new ObjectParameter("dni_huesped", dni_huesped) :
                new ObjectParameter("dni_huesped", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_UltimaObservacion_Result>("pa_UltimaObservacion", dni_huespedParameter);
        }
    
        public virtual int pa_InsertarHabitacion(Nullable<int> id_habitacion)
        {
            var id_habitacionParameter = id_habitacion.HasValue ?
                new ObjectParameter("id_habitacion", id_habitacion) :
                new ObjectParameter("id_habitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_InsertarHabitacion", id_habitacionParameter);
        }
    
        public virtual ObjectResult<pa_ListaHabitaciones_Result> pa_ListaHabitaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ListaHabitaciones_Result>("pa_ListaHabitaciones");
        }
    
        public virtual ObjectResult<pa_ListaHabitacionesPorEstado_Result> pa_ListaHabitacionesPorEstado(Nullable<System.DateTime> fecha, string estado)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ListaHabitacionesPorEstado_Result>("pa_ListaHabitacionesPorEstado", fechaParameter, estadoParameter);
        }
    
        public virtual int pa_CambiarHabitacion(Nullable<int> id_habitacion_DE, Nullable<int> id_habitacion_A, Nullable<int> id_reserva_DE, Nullable<int> id_reserva_A, Nullable<System.DateTime> fecha)
        {
            var id_habitacion_DEParameter = id_habitacion_DE.HasValue ?
                new ObjectParameter("id_habitacion_DE", id_habitacion_DE) :
                new ObjectParameter("id_habitacion_DE", typeof(int));
    
            var id_habitacion_AParameter = id_habitacion_A.HasValue ?
                new ObjectParameter("id_habitacion_A", id_habitacion_A) :
                new ObjectParameter("id_habitacion_A", typeof(int));
    
            var id_reserva_DEParameter = id_reserva_DE.HasValue ?
                new ObjectParameter("id_reserva_DE", id_reserva_DE) :
                new ObjectParameter("id_reserva_DE", typeof(int));
    
            var id_reserva_AParameter = id_reserva_A.HasValue ?
                new ObjectParameter("id_reserva_A", id_reserva_A) :
                new ObjectParameter("id_reserva_A", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CambiarHabitacion", id_habitacion_DEParameter, id_habitacion_AParameter, id_reserva_DEParameter, id_reserva_AParameter, fechaParameter);
        }
    
        public virtual int pa_ActualizarStock(Nullable<int> id_producto, Nullable<int> cantidad)
        {
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("id_producto", id_producto) :
                new ObjectParameter("id_producto", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_ActualizarStock", id_productoParameter, cantidadParameter);
        }
    
        public virtual int pa_DescuentaStock(Nullable<int> id_producto, Nullable<int> cantidad)
        {
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("id_producto", id_producto) :
                new ObjectParameter("id_producto", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_DescuentaStock", id_productoParameter, cantidadParameter);
        }
    
        public virtual int pa_PagarServicio(Nullable<int> id, Nullable<int> idUsuario, Nullable<int> idCajaDia, Nullable<bool> estado_factura)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var idCajaDiaParameter = idCajaDia.HasValue ?
                new ObjectParameter("idCajaDia", idCajaDia) :
                new ObjectParameter("idCajaDia", typeof(int));
    
            var estado_facturaParameter = estado_factura.HasValue ?
                new ObjectParameter("estado_factura", estado_factura) :
                new ObjectParameter("estado_factura", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_PagarServicio", idParameter, idUsuarioParameter, idCajaDiaParameter, estado_facturaParameter);
        }
    
        public virtual ObjectResult<pa_CajaPedidos_Result> pa_CajaPedidos(Nullable<int> id_caja_dia, Nullable<System.DateTime> fecha_pago)
        {
            var id_caja_diaParameter = id_caja_dia.HasValue ?
                new ObjectParameter("id_caja_dia", id_caja_dia) :
                new ObjectParameter("id_caja_dia", typeof(int));
    
            var fecha_pagoParameter = fecha_pago.HasValue ?
                new ObjectParameter("fecha_pago", fecha_pago) :
                new ObjectParameter("fecha_pago", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CajaPedidos_Result>("pa_CajaPedidos", id_caja_diaParameter, fecha_pagoParameter);
        }
    
        public virtual ObjectResult<pa_PedidoPorDetalleReserva_Result> pa_PedidoPorDetalleReserva(Nullable<int> id_detalle_reserva)
        {
            var id_detalle_reservaParameter = id_detalle_reserva.HasValue ?
                new ObjectParameter("id_detalle_reserva", id_detalle_reserva) :
                new ObjectParameter("id_detalle_reserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_PedidoPorDetalleReserva_Result>("pa_PedidoPorDetalleReserva", id_detalle_reservaParameter);
        }
    
        public virtual int pa_CancelaMontoACuenta(Nullable<int> codigo_reserva)
        {
            var codigo_reservaParameter = codigo_reserva.HasValue ?
                new ObjectParameter("codigo_reserva", codigo_reserva) :
                new ObjectParameter("codigo_reserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CancelaMontoACuenta", codigo_reservaParameter);
        }
    
        public virtual int pa_UpdateComprobante(Nullable<int> id_liquidacion, string serie_liquidacion, string correlativo_liquidacion)
        {
            var id_liquidacionParameter = id_liquidacion.HasValue ?
                new ObjectParameter("id_liquidacion", id_liquidacion) :
                new ObjectParameter("id_liquidacion", typeof(int));
    
            var serie_liquidacionParameter = serie_liquidacion != null ?
                new ObjectParameter("serie_liquidacion", serie_liquidacion) :
                new ObjectParameter("serie_liquidacion", typeof(string));
    
            var correlativo_liquidacionParameter = correlativo_liquidacion != null ?
                new ObjectParameter("correlativo_liquidacion", correlativo_liquidacion) :
                new ObjectParameter("correlativo_liquidacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_UpdateComprobante", id_liquidacionParameter, serie_liquidacionParameter, correlativo_liquidacionParameter);
        }
    
        public virtual int pa_MovimientoEstados(Nullable<int> id_reserva, Nullable<int> id_usuario, Nullable<System.DateTime> fecha_movimiento, Nullable<int> dni_huesped, string estado_habitacion_reserva)
        {
            var id_reservaParameter = id_reserva.HasValue ?
                new ObjectParameter("id_reserva", id_reserva) :
                new ObjectParameter("id_reserva", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var fecha_movimientoParameter = fecha_movimiento.HasValue ?
                new ObjectParameter("fecha_movimiento", fecha_movimiento) :
                new ObjectParameter("fecha_movimiento", typeof(System.DateTime));
    
            var dni_huespedParameter = dni_huesped.HasValue ?
                new ObjectParameter("dni_huesped", dni_huesped) :
                new ObjectParameter("dni_huesped", typeof(int));
    
            var estado_habitacion_reservaParameter = estado_habitacion_reserva != null ?
                new ObjectParameter("estado_habitacion_reserva", estado_habitacion_reserva) :
                new ObjectParameter("estado_habitacion_reserva", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_MovimientoEstados", id_reservaParameter, id_usuarioParameter, fecha_movimientoParameter, dni_huespedParameter, estado_habitacion_reservaParameter);
        }
    
        public virtual int pa_CierreCajaDia(Nullable<int> id_caja_dia, Nullable<int> usuario_cierre, Nullable<decimal> saldo_final, Nullable<decimal> saldo_diferencia, Nullable<decimal> saldo_egreso_caja_dia)
        {
            var id_caja_diaParameter = id_caja_dia.HasValue ?
                new ObjectParameter("id_caja_dia", id_caja_dia) :
                new ObjectParameter("id_caja_dia", typeof(int));
    
            var usuario_cierreParameter = usuario_cierre.HasValue ?
                new ObjectParameter("usuario_cierre", usuario_cierre) :
                new ObjectParameter("usuario_cierre", typeof(int));
    
            var saldo_finalParameter = saldo_final.HasValue ?
                new ObjectParameter("saldo_final", saldo_final) :
                new ObjectParameter("saldo_final", typeof(decimal));
    
            var saldo_diferenciaParameter = saldo_diferencia.HasValue ?
                new ObjectParameter("saldo_diferencia", saldo_diferencia) :
                new ObjectParameter("saldo_diferencia", typeof(decimal));
    
            var saldo_egreso_caja_diaParameter = saldo_egreso_caja_dia.HasValue ?
                new ObjectParameter("saldo_egreso_caja_dia", saldo_egreso_caja_dia) :
                new ObjectParameter("saldo_egreso_caja_dia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CierreCajaDia", id_caja_diaParameter, usuario_cierreParameter, saldo_finalParameter, saldo_diferenciaParameter, saldo_egreso_caja_diaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> pa_TotalEgresoByIdCajaDia(Nullable<int> id_caja_dia)
        {
            var id_caja_diaParameter = id_caja_dia.HasValue ?
                new ObjectParameter("id_caja_dia", id_caja_dia) :
                new ObjectParameter("id_caja_dia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("pa_TotalEgresoByIdCajaDia", id_caja_diaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> pa_TotalMontoACuentaByIdCajaDia(Nullable<int> id_caja_dia)
        {
            var id_caja_diaParameter = id_caja_dia.HasValue ?
                new ObjectParameter("id_caja_dia", id_caja_dia) :
                new ObjectParameter("id_caja_dia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("pa_TotalMontoACuentaByIdCajaDia", id_caja_diaParameter);
        }
    
        public virtual ObjectResult<pa_TotalServiciosByIdCajaDia_Result> pa_TotalServiciosByIdCajaDia(Nullable<int> id_caja_dia)
        {
            var id_caja_diaParameter = id_caja_dia.HasValue ?
                new ObjectParameter("id_caja_dia", id_caja_dia) :
                new ObjectParameter("id_caja_dia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_TotalServiciosByIdCajaDia_Result>("pa_TotalServiciosByIdCajaDia", id_caja_diaParameter);
        }
    
        public virtual int pa_TerminarHospedaje(Nullable<int> id_reserva)
        {
            var id_reservaParameter = id_reserva.HasValue ?
                new ObjectParameter("id_reserva", id_reserva) :
                new ObjectParameter("id_reserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_TerminarHospedaje", id_reservaParameter);
        }
    
        public virtual int pa_RemueveTarjeta(Nullable<int> id_liquidacion)
        {
            var id_liquidacionParameter = id_liquidacion.HasValue ?
                new ObjectParameter("id_liquidacion", id_liquidacion) :
                new ObjectParameter("id_liquidacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_RemueveTarjeta", id_liquidacionParameter);
        }
    
        public virtual ObjectResult<pa_ValidarTarjetas_Result> pa_ValidarTarjetas(Nullable<System.DateTime> f_inicio, Nullable<System.DateTime> f_final)
        {
            var f_inicioParameter = f_inicio.HasValue ?
                new ObjectParameter("F_inicio", f_inicio) :
                new ObjectParameter("F_inicio", typeof(System.DateTime));
    
            var f_finalParameter = f_final.HasValue ?
                new ObjectParameter("F_final", f_final) :
                new ObjectParameter("F_final", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ValidarTarjetas_Result>("pa_ValidarTarjetas", f_inicioParameter, f_finalParameter);
        }
    
        public virtual int pa_ActualizarPermiso(Nullable<int> id_rol, string permisos)
        {
            var id_rolParameter = id_rol.HasValue ?
                new ObjectParameter("id_rol", id_rol) :
                new ObjectParameter("id_rol", typeof(int));
    
            var permisosParameter = permisos != null ?
                new ObjectParameter("permisos", permisos) :
                new ObjectParameter("permisos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_ActualizarPermiso", id_rolParameter, permisosParameter);
        }
    
        public virtual int pa_GenerarMes(Nullable<int> id_habitacion, Nullable<int> dia, string mes, string anio, string checkIn, string checkOut)
        {
            var id_habitacionParameter = id_habitacion.HasValue ?
                new ObjectParameter("id_habitacion", id_habitacion) :
                new ObjectParameter("id_habitacion", typeof(int));
    
            var diaParameter = dia.HasValue ?
                new ObjectParameter("dia", dia) :
                new ObjectParameter("dia", typeof(int));
    
            var mesParameter = mes != null ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(string));
    
            var anioParameter = anio != null ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(string));
    
            var checkInParameter = checkIn != null ?
                new ObjectParameter("checkIn", checkIn) :
                new ObjectParameter("checkIn", typeof(string));
    
            var checkOutParameter = checkOut != null ?
                new ObjectParameter("checkOut", checkOut) :
                new ObjectParameter("checkOut", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_GenerarMes", id_habitacionParameter, diaParameter, mesParameter, anioParameter, checkInParameter, checkOutParameter);
        }
    
        public virtual ObjectResult<pa_ListaHabitacionesPorFecha_Result> pa_ListaHabitacionesPorFecha(Nullable<System.DateTime> fecha_inicio_reserva)
        {
            var fecha_inicio_reservaParameter = fecha_inicio_reserva.HasValue ?
                new ObjectParameter("fecha_inicio_reserva", fecha_inicio_reserva) :
                new ObjectParameter("fecha_inicio_reserva", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ListaHabitacionesPorFecha_Result>("pa_ListaHabitacionesPorFecha", fecha_inicio_reservaParameter);
        }
    
        public virtual int pa_PagoReserva(Nullable<int> idReserva)
        {
            var idReservaParameter = idReserva.HasValue ?
                new ObjectParameter("idReserva", idReserva) :
                new ObjectParameter("idReserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_PagoReserva", idReservaParameter);
        }
    
        public virtual int pa_ActualizaFechaHotelera(Nullable<System.DateTime> fecha_hotelera)
        {
            var fecha_hoteleraParameter = fecha_hotelera.HasValue ?
                new ObjectParameter("fecha_hotelera", fecha_hotelera) :
                new ObjectParameter("fecha_hotelera", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_ActualizaFechaHotelera", fecha_hoteleraParameter);
        }
    
        public virtual int pa_DesregistraAuto(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_DesregistraAuto", idParameter);
        }
    
        public virtual int pa_RegistraAuto(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_RegistraAuto", idParameter);
        }
    
        public virtual int pa_RegistroReservacionOut(Nullable<int> id, Nullable<int> id_usuario, string estado_habitacion_reserva)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var estado_habitacion_reservaParameter = estado_habitacion_reserva != null ?
                new ObjectParameter("estado_habitacion_reserva", estado_habitacion_reserva) :
                new ObjectParameter("estado_habitacion_reserva", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_RegistroReservacionOut", idParameter, id_usuarioParameter, estado_habitacion_reservaParameter);
        }
    
        public virtual int pa_CambiarEstadoSinHuesped(Nullable<int> id, string estado_habitacion_reserva)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var estado_habitacion_reservaParameter = estado_habitacion_reserva != null ?
                new ObjectParameter("estado_habitacion_reserva", estado_habitacion_reserva) :
                new ObjectParameter("estado_habitacion_reserva", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CambiarEstadoSinHuesped", idParameter, estado_habitacion_reservaParameter);
        }
    
        public virtual int pa_CancelarHospedaje(Nullable<int> id_reserva)
        {
            var id_reservaParameter = id_reserva.HasValue ?
                new ObjectParameter("id_reserva", id_reserva) :
                new ObjectParameter("id_reserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CancelarHospedaje", id_reservaParameter);
        }
    
        public virtual ObjectResult<pa_PedidoPorDNI_Result> pa_PedidoPorDNI(Nullable<int> dni_huesped)
        {
            var dni_huespedParameter = dni_huesped.HasValue ?
                new ObjectParameter("dni_huesped", dni_huesped) :
                new ObjectParameter("dni_huesped", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_PedidoPorDNI_Result>("pa_PedidoPorDNI", dni_huespedParameter);
        }
    
        public virtual ObjectResult<pa_PagarHospedaje_Result> pa_PagarHospedaje(Nullable<int> codigo_reserva)
        {
            var codigo_reservaParameter = codigo_reserva.HasValue ?
                new ObjectParameter("codigo_reserva", codigo_reserva) :
                new ObjectParameter("codigo_reserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_PagarHospedaje_Result>("pa_PagarHospedaje", codigo_reservaParameter);
        }
    
        public virtual int pa_CambiarEstadoGrupo(Nullable<int> id_grupo, string estado_habitacion_reserva)
        {
            var id_grupoParameter = id_grupo.HasValue ?
                new ObjectParameter("id_grupo", id_grupo) :
                new ObjectParameter("id_grupo", typeof(int));
    
            var estado_habitacion_reservaParameter = estado_habitacion_reserva != null ?
                new ObjectParameter("estado_habitacion_reserva", estado_habitacion_reserva) :
                new ObjectParameter("estado_habitacion_reserva", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CambiarEstadoGrupo", id_grupoParameter, estado_habitacion_reservaParameter);
        }
    
        public virtual ObjectResult<string> pa_MontoLetras(Nullable<decimal> mONTO)
        {
            var mONTOParameter = mONTO.HasValue ?
                new ObjectParameter("MONTO", mONTO) :
                new ObjectParameter("MONTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pa_MontoLetras", mONTOParameter);
        }
    
        public virtual int pa_Observacion(Nullable<int> id, string observacion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("observacion", observacion) :
                new ObjectParameter("observacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Observacion", idParameter, observacionParameter);
        }
    
        public virtual int pa_RegistroReservacionMismo(Nullable<int> id, Nullable<int> id_tarifa_habitacion, Nullable<int> id_usuario, Nullable<bool> estado_pago_reserva, string estado_habitacion_reserva, Nullable<int> dia, Nullable<int> codigo, Nullable<System.DateTime> fechaOut, Nullable<int> grupo, string observacion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_tarifa_habitacionParameter = id_tarifa_habitacion.HasValue ?
                new ObjectParameter("id_tarifa_habitacion", id_tarifa_habitacion) :
                new ObjectParameter("id_tarifa_habitacion", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var estado_pago_reservaParameter = estado_pago_reserva.HasValue ?
                new ObjectParameter("estado_pago_reserva", estado_pago_reserva) :
                new ObjectParameter("estado_pago_reserva", typeof(bool));
    
            var estado_habitacion_reservaParameter = estado_habitacion_reserva != null ?
                new ObjectParameter("estado_habitacion_reserva", estado_habitacion_reserva) :
                new ObjectParameter("estado_habitacion_reserva", typeof(string));
    
            var diaParameter = dia.HasValue ?
                new ObjectParameter("dia", dia) :
                new ObjectParameter("dia", typeof(int));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var fechaOutParameter = fechaOut.HasValue ?
                new ObjectParameter("fechaOut", fechaOut) :
                new ObjectParameter("fechaOut", typeof(System.DateTime));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("observacion", observacion) :
                new ObjectParameter("observacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_RegistroReservacionMismo", idParameter, id_tarifa_habitacionParameter, id_usuarioParameter, estado_pago_reservaParameter, estado_habitacion_reservaParameter, diaParameter, codigoParameter, fechaOutParameter, grupoParameter, observacionParameter);
        }
    
        public virtual int pa_PagoParcialHospedaje(Nullable<int> id_reserva)
        {
            var id_reservaParameter = id_reserva.HasValue ?
                new ObjectParameter("id_reserva", id_reserva) :
                new ObjectParameter("id_reserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_PagoParcialHospedaje", id_reservaParameter);
        }
    
        public virtual int pa_Anular_Comprobante(Nullable<int> idLiquidacion)
        {
            var idLiquidacionParameter = idLiquidacion.HasValue ?
                new ObjectParameter("idLiquidacion", idLiquidacion) :
                new ObjectParameter("idLiquidacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Anular_Comprobante", idLiquidacionParameter);
        }
    
        public virtual ObjectResult<pa_PagarHospedajeHistorico_Result> pa_PagarHospedajeHistorico(Nullable<int> codigo_reserva)
        {
            var codigo_reservaParameter = codigo_reserva.HasValue ?
                new ObjectParameter("codigo_reserva", codigo_reserva) :
                new ObjectParameter("codigo_reserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_PagarHospedajeHistorico_Result>("pa_PagarHospedajeHistorico", codigo_reservaParameter);
        }
    
        public virtual int pa_EditarTarifa(Nullable<int> idGrupo, Nullable<int> idTarifa)
        {
            var idGrupoParameter = idGrupo.HasValue ?
                new ObjectParameter("idGrupo", idGrupo) :
                new ObjectParameter("idGrupo", typeof(int));
    
            var idTarifaParameter = idTarifa.HasValue ?
                new ObjectParameter("idTarifa", idTarifa) :
                new ObjectParameter("idTarifa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_EditarTarifa", idGrupoParameter, idTarifaParameter);
        }
    
        public virtual int pa_CambiarEstadoGrupo_2(Nullable<int> id_grupo, string estado_habitacion_reserva)
        {
            var id_grupoParameter = id_grupo.HasValue ?
                new ObjectParameter("id_grupo", id_grupo) :
                new ObjectParameter("id_grupo", typeof(int));
    
            var estado_habitacion_reservaParameter = estado_habitacion_reserva != null ?
                new ObjectParameter("estado_habitacion_reserva", estado_habitacion_reserva) :
                new ObjectParameter("estado_habitacion_reserva", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CambiarEstadoGrupo_2", id_grupoParameter, estado_habitacion_reservaParameter);
        }
    
        public virtual ObjectResult<pa_UnirFactura_Result> pa_UnirFactura()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_UnirFactura_Result>("pa_UnirFactura");
        }
    
        public virtual ObjectResult<pa_TotalHotelByIdCajaDia_Result> pa_TotalHotelByIdCajaDia(Nullable<int> id_caja_dia)
        {
            var id_caja_diaParameter = id_caja_dia.HasValue ?
                new ObjectParameter("id_caja_dia", id_caja_dia) :
                new ObjectParameter("id_caja_dia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_TotalHotelByIdCajaDia_Result>("pa_TotalHotelByIdCajaDia", id_caja_diaParameter);
        }
    
        public virtual int pa_RegistroReservacion(Nullable<int> id, Nullable<int> id_tarifa_habitacion, Nullable<int> id_usuario, Nullable<bool> estado_pago_reserva, string estado_habitacion_reserva, Nullable<int> dia, Nullable<int> codigo, Nullable<int> grupo, string observacion, Nullable<System.DateTime> fechaSalida)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_tarifa_habitacionParameter = id_tarifa_habitacion.HasValue ?
                new ObjectParameter("id_tarifa_habitacion", id_tarifa_habitacion) :
                new ObjectParameter("id_tarifa_habitacion", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var estado_pago_reservaParameter = estado_pago_reserva.HasValue ?
                new ObjectParameter("estado_pago_reserva", estado_pago_reserva) :
                new ObjectParameter("estado_pago_reserva", typeof(bool));
    
            var estado_habitacion_reservaParameter = estado_habitacion_reserva != null ?
                new ObjectParameter("estado_habitacion_reserva", estado_habitacion_reserva) :
                new ObjectParameter("estado_habitacion_reserva", typeof(string));
    
            var diaParameter = dia.HasValue ?
                new ObjectParameter("dia", dia) :
                new ObjectParameter("dia", typeof(int));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var grupoParameter = grupo.HasValue ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(int));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("observacion", observacion) :
                new ObjectParameter("observacion", typeof(string));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_RegistroReservacion", idParameter, id_tarifa_habitacionParameter, id_usuarioParameter, estado_pago_reservaParameter, estado_habitacion_reservaParameter, diaParameter, codigoParameter, grupoParameter, observacionParameter, fechaSalidaParameter);
        }
    
        public virtual ObjectResult<pa_MontoACuenta_Result> pa_MontoACuenta(Nullable<int> id_grupo)
        {
            var id_grupoParameter = id_grupo.HasValue ?
                new ObjectParameter("id_grupo", id_grupo) :
                new ObjectParameter("id_grupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_MontoACuenta_Result>("pa_MontoACuenta", id_grupoParameter);
        }
    
        public virtual int pa_MontoACuentaEnCaja(Nullable<int> id_montoCuenta)
        {
            var id_montoCuentaParameter = id_montoCuenta.HasValue ?
                new ObjectParameter("id_montoCuenta", id_montoCuenta) :
                new ObjectParameter("id_montoCuenta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_MontoACuentaEnCaja", id_montoCuentaParameter);
        }
    
        public virtual ObjectResult<pa_ReporteBalance_Result> pa_ReporteBalance(Nullable<int> aNIO, string mOSTRAR)
        {
            var aNIOParameter = aNIO.HasValue ?
                new ObjectParameter("ANIO", aNIO) :
                new ObjectParameter("ANIO", typeof(int));
    
            var mOSTRARParameter = mOSTRAR != null ?
                new ObjectParameter("MOSTRAR", mOSTRAR) :
                new ObjectParameter("MOSTRAR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ReporteBalance_Result>("pa_ReporteBalance", aNIOParameter, mOSTRARParameter);
        }
    
        public virtual int pa_Anular_LiquidacionConsumo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Anular_LiquidacionConsumo", idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> pa_TotalDescuentoByIdCajaDia(Nullable<int> id_caja_dia)
        {
            var id_caja_diaParameter = id_caja_dia.HasValue ?
                new ObjectParameter("id_caja_dia", id_caja_dia) :
                new ObjectParameter("id_caja_dia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("pa_TotalDescuentoByIdCajaDia", id_caja_diaParameter);
        }
    
        public virtual ObjectResult<pa_ReporteContador_Result> pa_ReporteContador(Nullable<System.DateTime> fecha_inicial, Nullable<System.DateTime> fecha_final)
        {
            var fecha_inicialParameter = fecha_inicial.HasValue ?
                new ObjectParameter("fecha_inicial", fecha_inicial) :
                new ObjectParameter("fecha_inicial", typeof(System.DateTime));
    
            var fecha_finalParameter = fecha_final.HasValue ?
                new ObjectParameter("fecha_final", fecha_final) :
                new ObjectParameter("fecha_final", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ReporteContador_Result>("pa_ReporteContador", fecha_inicialParameter, fecha_finalParameter);
        }
    
        public virtual ObjectResult<pa_ReporteBalanceResumen_Result> pa_ReporteBalanceResumen(Nullable<int> aNIO, Nullable<decimal> dOLAR)
        {
            var aNIOParameter = aNIO.HasValue ?
                new ObjectParameter("ANIO", aNIO) :
                new ObjectParameter("ANIO", typeof(int));
    
            var dOLARParameter = dOLAR.HasValue ?
                new ObjectParameter("DOLAR", dOLAR) :
                new ObjectParameter("DOLAR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ReporteBalanceResumen_Result>("pa_ReporteBalanceResumen", aNIOParameter, dOLARParameter);
        }
    
        public virtual ObjectResult<pa_ReporteContadorEntregable_Result> pa_ReporteContadorEntregable(Nullable<System.DateTime> fecha_inicial, Nullable<System.DateTime> fecha_final)
        {
            var fecha_inicialParameter = fecha_inicial.HasValue ?
                new ObjectParameter("fecha_inicial", fecha_inicial) :
                new ObjectParameter("fecha_inicial", typeof(System.DateTime));
    
            var fecha_finalParameter = fecha_final.HasValue ?
                new ObjectParameter("fecha_final", fecha_final) :
                new ObjectParameter("fecha_final", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ReporteContadorEntregable_Result>("pa_ReporteContadorEntregable", fecha_inicialParameter, fecha_finalParameter);
        }
    
        public virtual ObjectResult<pa_ListaComprobantesConsumo_Result> pa_ListaComprobantesConsumo(Nullable<System.DateTime> fecha_inicial, Nullable<System.DateTime> fecha_final)
        {
            var fecha_inicialParameter = fecha_inicial.HasValue ?
                new ObjectParameter("fecha_inicial", fecha_inicial) :
                new ObjectParameter("fecha_inicial", typeof(System.DateTime));
    
            var fecha_finalParameter = fecha_final.HasValue ?
                new ObjectParameter("fecha_final", fecha_final) :
                new ObjectParameter("fecha_final", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ListaComprobantesConsumo_Result>("pa_ListaComprobantesConsumo", fecha_inicialParameter, fecha_finalParameter);
        }
    
        public virtual ObjectResult<pa_ListaComprobantesLiquidacion_Result> pa_ListaComprobantesLiquidacion(Nullable<System.DateTime> fecha_inicial, Nullable<System.DateTime> fecha_final)
        {
            var fecha_inicialParameter = fecha_inicial.HasValue ?
                new ObjectParameter("fecha_inicial", fecha_inicial) :
                new ObjectParameter("fecha_inicial", typeof(System.DateTime));
    
            var fecha_finalParameter = fecha_final.HasValue ?
                new ObjectParameter("fecha_final", fecha_final) :
                new ObjectParameter("fecha_final", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ListaComprobantesLiquidacion_Result>("pa_ListaComprobantesLiquidacion", fecha_inicialParameter, fecha_finalParameter);
        }
    
        public virtual int UpdateLiquidacion(Nullable<int> id_liquidacion, string tipo_comprobante_liquidacion, string serie_liquidacion, string correlativo_liquidacion, string forma_pago_liquidacion, Nullable<decimal> sub_total_liquidacion, Nullable<decimal> igv_liquidacion, Nullable<decimal> total_liquidacion, string referencia_liquidacion, string ntarjeta_liquidacion)
        {
            var id_liquidacionParameter = id_liquidacion.HasValue ?
                new ObjectParameter("id_liquidacion", id_liquidacion) :
                new ObjectParameter("id_liquidacion", typeof(int));
    
            var tipo_comprobante_liquidacionParameter = tipo_comprobante_liquidacion != null ?
                new ObjectParameter("tipo_comprobante_liquidacion", tipo_comprobante_liquidacion) :
                new ObjectParameter("tipo_comprobante_liquidacion", typeof(string));
    
            var serie_liquidacionParameter = serie_liquidacion != null ?
                new ObjectParameter("serie_liquidacion", serie_liquidacion) :
                new ObjectParameter("serie_liquidacion", typeof(string));
    
            var correlativo_liquidacionParameter = correlativo_liquidacion != null ?
                new ObjectParameter("correlativo_liquidacion", correlativo_liquidacion) :
                new ObjectParameter("correlativo_liquidacion", typeof(string));
    
            var forma_pago_liquidacionParameter = forma_pago_liquidacion != null ?
                new ObjectParameter("forma_pago_liquidacion", forma_pago_liquidacion) :
                new ObjectParameter("forma_pago_liquidacion", typeof(string));
    
            var sub_total_liquidacionParameter = sub_total_liquidacion.HasValue ?
                new ObjectParameter("sub_total_liquidacion", sub_total_liquidacion) :
                new ObjectParameter("sub_total_liquidacion", typeof(decimal));
    
            var igv_liquidacionParameter = igv_liquidacion.HasValue ?
                new ObjectParameter("igv_liquidacion", igv_liquidacion) :
                new ObjectParameter("igv_liquidacion", typeof(decimal));
    
            var total_liquidacionParameter = total_liquidacion.HasValue ?
                new ObjectParameter("total_liquidacion", total_liquidacion) :
                new ObjectParameter("total_liquidacion", typeof(decimal));
    
            var referencia_liquidacionParameter = referencia_liquidacion != null ?
                new ObjectParameter("referencia_liquidacion", referencia_liquidacion) :
                new ObjectParameter("referencia_liquidacion", typeof(string));
    
            var ntarjeta_liquidacionParameter = ntarjeta_liquidacion != null ?
                new ObjectParameter("ntarjeta_liquidacion", ntarjeta_liquidacion) :
                new ObjectParameter("ntarjeta_liquidacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateLiquidacion", id_liquidacionParameter, tipo_comprobante_liquidacionParameter, serie_liquidacionParameter, correlativo_liquidacionParameter, forma_pago_liquidacionParameter, sub_total_liquidacionParameter, igv_liquidacionParameter, total_liquidacionParameter, referencia_liquidacionParameter, ntarjeta_liquidacionParameter);
        }
    
        public virtual int UpdateConsumo(Nullable<int> id_liquidacion, string tipo_comprobante_liquidacion, string serie_liquidacion, string correlativo_liquidacion, string forma_pago_liquidacion, Nullable<decimal> sub_total_liquidacion, Nullable<decimal> igv_liquidacion, Nullable<decimal> total_liquidacion, string referencia_liquidacion, string ntarjeta_liquidacion)
        {
            var id_liquidacionParameter = id_liquidacion.HasValue ?
                new ObjectParameter("id_liquidacion", id_liquidacion) :
                new ObjectParameter("id_liquidacion", typeof(int));
    
            var tipo_comprobante_liquidacionParameter = tipo_comprobante_liquidacion != null ?
                new ObjectParameter("tipo_comprobante_liquidacion", tipo_comprobante_liquidacion) :
                new ObjectParameter("tipo_comprobante_liquidacion", typeof(string));
    
            var serie_liquidacionParameter = serie_liquidacion != null ?
                new ObjectParameter("serie_liquidacion", serie_liquidacion) :
                new ObjectParameter("serie_liquidacion", typeof(string));
    
            var correlativo_liquidacionParameter = correlativo_liquidacion != null ?
                new ObjectParameter("correlativo_liquidacion", correlativo_liquidacion) :
                new ObjectParameter("correlativo_liquidacion", typeof(string));
    
            var forma_pago_liquidacionParameter = forma_pago_liquidacion != null ?
                new ObjectParameter("forma_pago_liquidacion", forma_pago_liquidacion) :
                new ObjectParameter("forma_pago_liquidacion", typeof(string));
    
            var sub_total_liquidacionParameter = sub_total_liquidacion.HasValue ?
                new ObjectParameter("sub_total_liquidacion", sub_total_liquidacion) :
                new ObjectParameter("sub_total_liquidacion", typeof(decimal));
    
            var igv_liquidacionParameter = igv_liquidacion.HasValue ?
                new ObjectParameter("igv_liquidacion", igv_liquidacion) :
                new ObjectParameter("igv_liquidacion", typeof(decimal));
    
            var total_liquidacionParameter = total_liquidacion.HasValue ?
                new ObjectParameter("total_liquidacion", total_liquidacion) :
                new ObjectParameter("total_liquidacion", typeof(decimal));
    
            var referencia_liquidacionParameter = referencia_liquidacion != null ?
                new ObjectParameter("referencia_liquidacion", referencia_liquidacion) :
                new ObjectParameter("referencia_liquidacion", typeof(string));
    
            var ntarjeta_liquidacionParameter = ntarjeta_liquidacion != null ?
                new ObjectParameter("ntarjeta_liquidacion", ntarjeta_liquidacion) :
                new ObjectParameter("ntarjeta_liquidacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateConsumo", id_liquidacionParameter, tipo_comprobante_liquidacionParameter, serie_liquidacionParameter, correlativo_liquidacionParameter, forma_pago_liquidacionParameter, sub_total_liquidacionParameter, igv_liquidacionParameter, total_liquidacionParameter, referencia_liquidacionParameter, ntarjeta_liquidacionParameter);
        }
    
        public virtual int GenerarBk()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerarBk");
        }
    
        public virtual ObjectResult<pa_HuespedRepetidos_Result> pa_HuespedRepetidos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_HuespedRepetidos_Result>("pa_HuespedRepetidos");
        }
    
        public virtual int pa_RemoverDuplicado(Nullable<int> iD_HUESPED)
        {
            var iD_HUESPEDParameter = iD_HUESPED.HasValue ?
                new ObjectParameter("ID_HUESPED", iD_HUESPED) :
                new ObjectParameter("ID_HUESPED", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_RemoverDuplicado", iD_HUESPEDParameter);
        }
    
        public virtual ObjectResult<pa_ListaComprobantesTarjetas_Result> pa_ListaComprobantesTarjetas(Nullable<System.DateTime> fecha_inicial, Nullable<System.DateTime> fecha_final)
        {
            var fecha_inicialParameter = fecha_inicial.HasValue ?
                new ObjectParameter("fecha_inicial", fecha_inicial) :
                new ObjectParameter("fecha_inicial", typeof(System.DateTime));
    
            var fecha_finalParameter = fecha_final.HasValue ?
                new ObjectParameter("fecha_final", fecha_final) :
                new ObjectParameter("fecha_final", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ListaComprobantesTarjetas_Result>("pa_ListaComprobantesTarjetas", fecha_inicialParameter, fecha_finalParameter);
        }
    
        public virtual int UpdateMontoTarjeta(Nullable<int> id, string forma_pago_liquidacion, Nullable<decimal> total_liquidacion, string referencia_liquidacion, string ntarjeta_liquidacion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var forma_pago_liquidacionParameter = forma_pago_liquidacion != null ?
                new ObjectParameter("forma_pago_liquidacion", forma_pago_liquidacion) :
                new ObjectParameter("forma_pago_liquidacion", typeof(string));
    
            var total_liquidacionParameter = total_liquidacion.HasValue ?
                new ObjectParameter("total_liquidacion", total_liquidacion) :
                new ObjectParameter("total_liquidacion", typeof(decimal));
    
            var referencia_liquidacionParameter = referencia_liquidacion != null ?
                new ObjectParameter("referencia_liquidacion", referencia_liquidacion) :
                new ObjectParameter("referencia_liquidacion", typeof(string));
    
            var ntarjeta_liquidacionParameter = ntarjeta_liquidacion != null ?
                new ObjectParameter("ntarjeta_liquidacion", ntarjeta_liquidacion) :
                new ObjectParameter("ntarjeta_liquidacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMontoTarjeta", idParameter, forma_pago_liquidacionParameter, total_liquidacionParameter, referencia_liquidacionParameter, ntarjeta_liquidacionParameter);
        }
    
        public virtual int pa_BorrarContadorConsumo(Nullable<int> id_liquidacion)
        {
            var id_liquidacionParameter = id_liquidacion.HasValue ?
                new ObjectParameter("id_liquidacion", id_liquidacion) :
                new ObjectParameter("id_liquidacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_BorrarContadorConsumo", id_liquidacionParameter);
        }
    
        public virtual int pa_BorrarContadorLiquidacion(Nullable<int> id_liquidacion)
        {
            var id_liquidacionParameter = id_liquidacion.HasValue ?
                new ObjectParameter("id_liquidacion", id_liquidacion) :
                new ObjectParameter("id_liquidacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_BorrarContadorLiquidacion", id_liquidacionParameter);
        }
    
        public virtual ObjectResult<string> pa_GenerarDNI_Extranjero()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pa_GenerarDNI_Extranjero");
        }
    
        public virtual ObjectResult<pa_BusquedaHistorico_Result> pa_BusquedaHistorico(string nombreHuesped)
        {
            var nombreHuespedParameter = nombreHuesped != null ?
                new ObjectParameter("NombreHuesped", nombreHuesped) :
                new ObjectParameter("NombreHuesped", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_BusquedaHistorico_Result>("pa_BusquedaHistorico", nombreHuespedParameter);
        }
    
        public virtual int UpdateLiquidacion_BOLETA(string nOMBRE, Nullable<int> id_liquidacion, string tipo_comprobante_liquidacion, string serie_liquidacion, string correlativo_liquidacion, string forma_pago_liquidacion, Nullable<decimal> sub_total_liquidacion, Nullable<decimal> igv_liquidacion, Nullable<decimal> total_liquidacion, string referencia_liquidacion, string ntarjeta_liquidacion)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var id_liquidacionParameter = id_liquidacion.HasValue ?
                new ObjectParameter("id_liquidacion", id_liquidacion) :
                new ObjectParameter("id_liquidacion", typeof(int));
    
            var tipo_comprobante_liquidacionParameter = tipo_comprobante_liquidacion != null ?
                new ObjectParameter("tipo_comprobante_liquidacion", tipo_comprobante_liquidacion) :
                new ObjectParameter("tipo_comprobante_liquidacion", typeof(string));
    
            var serie_liquidacionParameter = serie_liquidacion != null ?
                new ObjectParameter("serie_liquidacion", serie_liquidacion) :
                new ObjectParameter("serie_liquidacion", typeof(string));
    
            var correlativo_liquidacionParameter = correlativo_liquidacion != null ?
                new ObjectParameter("correlativo_liquidacion", correlativo_liquidacion) :
                new ObjectParameter("correlativo_liquidacion", typeof(string));
    
            var forma_pago_liquidacionParameter = forma_pago_liquidacion != null ?
                new ObjectParameter("forma_pago_liquidacion", forma_pago_liquidacion) :
                new ObjectParameter("forma_pago_liquidacion", typeof(string));
    
            var sub_total_liquidacionParameter = sub_total_liquidacion.HasValue ?
                new ObjectParameter("sub_total_liquidacion", sub_total_liquidacion) :
                new ObjectParameter("sub_total_liquidacion", typeof(decimal));
    
            var igv_liquidacionParameter = igv_liquidacion.HasValue ?
                new ObjectParameter("igv_liquidacion", igv_liquidacion) :
                new ObjectParameter("igv_liquidacion", typeof(decimal));
    
            var total_liquidacionParameter = total_liquidacion.HasValue ?
                new ObjectParameter("total_liquidacion", total_liquidacion) :
                new ObjectParameter("total_liquidacion", typeof(decimal));
    
            var referencia_liquidacionParameter = referencia_liquidacion != null ?
                new ObjectParameter("referencia_liquidacion", referencia_liquidacion) :
                new ObjectParameter("referencia_liquidacion", typeof(string));
    
            var ntarjeta_liquidacionParameter = ntarjeta_liquidacion != null ?
                new ObjectParameter("ntarjeta_liquidacion", ntarjeta_liquidacion) :
                new ObjectParameter("ntarjeta_liquidacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateLiquidacion_BOLETA", nOMBREParameter, id_liquidacionParameter, tipo_comprobante_liquidacionParameter, serie_liquidacionParameter, correlativo_liquidacionParameter, forma_pago_liquidacionParameter, sub_total_liquidacionParameter, igv_liquidacionParameter, total_liquidacionParameter, referencia_liquidacionParameter, ntarjeta_liquidacionParameter);
        }
    
        public virtual ObjectResult<pa_ObtieneCorrelativo_Result> pa_ObtieneCorrelativo(string i_pTIPO_COMPROBANTE)
        {
            var i_pTIPO_COMPROBANTEParameter = i_pTIPO_COMPROBANTE != null ?
                new ObjectParameter("I_pTIPO_COMPROBANTE", i_pTIPO_COMPROBANTE) :
                new ObjectParameter("I_pTIPO_COMPROBANTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ObtieneCorrelativo_Result>("pa_ObtieneCorrelativo", i_pTIPO_COMPROBANTEParameter);
        }
    
        public virtual ObjectResult<string> pa_NumberToLetters(Nullable<decimal> i_pTotal_Comprobante)
        {
            var i_pTotal_ComprobanteParameter = i_pTotal_Comprobante.HasValue ?
                new ObjectParameter("I_pTotal_Comprobante", i_pTotal_Comprobante) :
                new ObjectParameter("I_pTotal_Comprobante", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pa_NumberToLetters", i_pTotal_ComprobanteParameter);
        }
    
        public virtual int pa_EliminarComprobante(string i_pTipoDocumentoId, string i_pSerie, Nullable<int> i_pNumero)
        {
            var i_pTipoDocumentoIdParameter = i_pTipoDocumentoId != null ?
                new ObjectParameter("I_pTipoDocumentoId", i_pTipoDocumentoId) :
                new ObjectParameter("I_pTipoDocumentoId", typeof(string));
    
            var i_pSerieParameter = i_pSerie != null ?
                new ObjectParameter("I_pSerie", i_pSerie) :
                new ObjectParameter("I_pSerie", typeof(string));
    
            var i_pNumeroParameter = i_pNumero.HasValue ?
                new ObjectParameter("I_pNumero", i_pNumero) :
                new ObjectParameter("I_pNumero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_EliminarComprobante", i_pTipoDocumentoIdParameter, i_pSerieParameter, i_pNumeroParameter);
        }
    
        public virtual ObjectResult<pa_ObtieneEstadoComprobante_Result> pa_ObtieneEstadoComprobante(string i_pTipoDocumentoId, string i_pSerie, Nullable<int> i_pNumero)
        {
            var i_pTipoDocumentoIdParameter = i_pTipoDocumentoId != null ?
                new ObjectParameter("I_pTipoDocumentoId", i_pTipoDocumentoId) :
                new ObjectParameter("I_pTipoDocumentoId", typeof(string));
    
            var i_pSerieParameter = i_pSerie != null ?
                new ObjectParameter("I_pSerie", i_pSerie) :
                new ObjectParameter("I_pSerie", typeof(string));
    
            var i_pNumeroParameter = i_pNumero.HasValue ?
                new ObjectParameter("I_pNumero", i_pNumero) :
                new ObjectParameter("I_pNumero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_ObtieneEstadoComprobante_Result>("pa_ObtieneEstadoComprobante", i_pTipoDocumentoIdParameter, i_pSerieParameter, i_pNumeroParameter);
        }
    
        public virtual int UpdateConsumoTotales(Nullable<int> id_liquidacion, Nullable<decimal> sub_total_liquidacion, Nullable<decimal> igv_liquidacion, Nullable<decimal> total_liquidacion)
        {
            var id_liquidacionParameter = id_liquidacion.HasValue ?
                new ObjectParameter("id_liquidacion", id_liquidacion) :
                new ObjectParameter("id_liquidacion", typeof(int));
    
            var sub_total_liquidacionParameter = sub_total_liquidacion.HasValue ?
                new ObjectParameter("sub_total_liquidacion", sub_total_liquidacion) :
                new ObjectParameter("sub_total_liquidacion", typeof(decimal));
    
            var igv_liquidacionParameter = igv_liquidacion.HasValue ?
                new ObjectParameter("igv_liquidacion", igv_liquidacion) :
                new ObjectParameter("igv_liquidacion", typeof(decimal));
    
            var total_liquidacionParameter = total_liquidacion.HasValue ?
                new ObjectParameter("total_liquidacion", total_liquidacion) :
                new ObjectParameter("total_liquidacion", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateConsumoTotales", id_liquidacionParameter, sub_total_liquidacionParameter, igv_liquidacionParameter, total_liquidacionParameter);
        }
    
        public virtual int UpdateLiquidacionTotales(Nullable<int> id_liquidacion, Nullable<decimal> sub_total_liquidacion, Nullable<decimal> igv_liquidacion, Nullable<decimal> total_liquidacion)
        {
            var id_liquidacionParameter = id_liquidacion.HasValue ?
                new ObjectParameter("id_liquidacion", id_liquidacion) :
                new ObjectParameter("id_liquidacion", typeof(int));
    
            var sub_total_liquidacionParameter = sub_total_liquidacion.HasValue ?
                new ObjectParameter("sub_total_liquidacion", sub_total_liquidacion) :
                new ObjectParameter("sub_total_liquidacion", typeof(decimal));
    
            var igv_liquidacionParameter = igv_liquidacion.HasValue ?
                new ObjectParameter("igv_liquidacion", igv_liquidacion) :
                new ObjectParameter("igv_liquidacion", typeof(decimal));
    
            var total_liquidacionParameter = total_liquidacion.HasValue ?
                new ObjectParameter("total_liquidacion", total_liquidacion) :
                new ObjectParameter("total_liquidacion", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateLiquidacionTotales", id_liquidacionParameter, sub_total_liquidacionParameter, igv_liquidacionParameter, total_liquidacionParameter);
        }
    
        public virtual int RechazarDocumentoConsumo(Nullable<int> i_pId_Liquidacion)
        {
            var i_pId_LiquidacionParameter = i_pId_Liquidacion.HasValue ?
                new ObjectParameter("I_pId_Liquidacion", i_pId_Liquidacion) :
                new ObjectParameter("I_pId_Liquidacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RechazarDocumentoConsumo", i_pId_LiquidacionParameter);
        }
    
        public virtual int RechazarDocumentoHospedaje(Nullable<int> i_pId_Liquidacion)
        {
            var i_pId_LiquidacionParameter = i_pId_Liquidacion.HasValue ?
                new ObjectParameter("I_pId_Liquidacion", i_pId_Liquidacion) :
                new ObjectParameter("I_pId_Liquidacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RechazarDocumentoHospedaje", i_pId_LiquidacionParameter);
        }
    
        public virtual int pa_QuitarReserva(Nullable<int> i_pID_RESERVA)
        {
            var i_pID_RESERVAParameter = i_pID_RESERVA.HasValue ?
                new ObjectParameter("I_pID_RESERVA", i_pID_RESERVA) :
                new ObjectParameter("I_pID_RESERVA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_QuitarReserva", i_pID_RESERVAParameter);
        }
    }
}
